/**
 * Catalog of write actions that get recorded in the AuditLog.
 *
 * Mirrors the Prisma `AuditAction` enum. Kept in the domain layer
 * so services can reference it without importing `@prisma/client`.
 */
export enum AuditAction {
  // Inventory entities (used in later phases)
  ARTICLE_CREATED = 'ARTICLE_CREATED',
  ARTICLE_UPDATED = 'ARTICLE_UPDATED',
  ARTICLE_DELETED = 'ARTICLE_DELETED',
  CATEGORY_CREATED = 'CATEGORY_CREATED',
  CATEGORY_UPDATED = 'CATEGORY_UPDATED',
  CATEGORY_DELETED = 'CATEGORY_DELETED',
  WAREHOUSE_CREATED = 'WAREHOUSE_CREATED',
  WAREHOUSE_UPDATED = 'WAREHOUSE_UPDATED',
  WAREHOUSE_DELETED = 'WAREHOUSE_DELETED',
  SUPPLIER_CREATED = 'SUPPLIER_CREATED',
  SUPPLIER_UPDATED = 'SUPPLIER_UPDATED',
  SUPPLIER_DELETED = 'SUPPLIER_DELETED',
  PROCUREMENT_CREATED = 'PROCUREMENT_CREATED',
  CORRECTION_CREATED = 'CORRECTION_CREATED',
  TRANSFER_CREATED = 'TRANSFER_CREATED',

  // Sales (Phase 8a)
  SHIFT_CLOSED = 'SHIFT_CLOSED',
  SALE_CREATED = 'SALE_CREATED',

  // User / org actions (Phase 1)
  USER_INVITED = 'USER_INVITED',
  USER_ROLE_CHANGED = 'USER_ROLE_CHANGED',
  USER_DEACTIVATED = 'USER_DEACTIVATED',
  USER_REACTIVATED = 'USER_REACTIVATED',
  USER_PASSWORD_RESET = 'USER_PASSWORD_RESET',
  USER_PASSWORD_CHANGED = 'USER_PASSWORD_CHANGED',
  USER_LOGGED_IN = 'USER_LOGGED_IN',

  // Platform-admin actions (A3/A4)
  ADMIN_IMPERSONATED = 'ADMIN_IMPERSONATED',
  ADMIN_USER_PASSWORD_RESET = 'ADMIN_USER_PASSWORD_RESET',
  ADMIN_USER_UPDATED = 'ADMIN_USER_UPDATED',
  ADMIN_USER_DEACTIVATED = 'ADMIN_USER_DEACTIVATED',
  ADMIN_USER_REACTIVATED = 'ADMIN_USER_REACTIVATED',

  // AI Sloj 0 — predictions + shopping lists
  RECOMMENDATION_GENERATED = 'RECOMMENDATION_GENERATED',
  SHOPPING_LIST_CREATED = 'SHOPPING_LIST_CREATED',
  SHOPPING_LIST_COMPLETED = 'SHOPPING_LIST_COMPLETED',
  SHOPPING_LIST_CANCELLED = 'SHOPPING_LIST_CANCELLED',
  SHOPPING_LIST_ITEM_ADDED = 'SHOPPING_LIST_ITEM_ADDED',
  SHOPPING_LIST_ITEM_REMOVED = 'SHOPPING_LIST_ITEM_REMOVED',
  SHOPPING_LIST_ITEM_UPDATED = 'SHOPPING_LIST_ITEM_UPDATED',

  // Phase 9 — per-warehouse access (EMPLOYEE) + FOH stock targets
  USER_WAREHOUSE_ACCESS_GRANTED = 'USER_WAREHOUSE_ACCESS_GRANTED',
  USER_WAREHOUSE_ACCESS_REVOKED = 'USER_WAREHOUSE_ACCESS_REVOKED',
  WAREHOUSE_STOCK_TARGET_UPDATED = 'WAREHOUSE_STOCK_TARGET_UPDATED',
}
