/**
 * Stored refresh token record.
 *
 * The plaintext token is never stored — only its sha256 hash. The
 * plaintext is generated by `RefreshTokenCodec`, returned to the
 * client once, and discarded.
 */
export class RefreshTokenRecord {
  constructor(
    readonly id: string,
    readonly organizationId: string,
    readonly userId: string,
    readonly tokenHash: string,
    readonly expiresAt: Date,
    readonly revokedAt: Date | null,
    readonly createdAt: Date,
  ) {}

  isExpired(now: Date = new Date()): boolean {
    return this.expiresAt.getTime() <= now.getTime();
  }

  isRevoked(): boolean {
    return this.revokedAt !== null;
  }

  isUsable(now: Date = new Date()): boolean {
    return !this.isRevoked() && !this.isExpired(now);
  }
}
